#if !canImport(ObjectiveC)
import XCTest

extension ConcurrentArrayTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ConcurrentArrayTests = [
        ("test_subscriptGet_onSequentialEnvironment_fromDictionaryContainingValueAtIndex_mustReturnValue", test_subscriptGet_onSequentialEnvironment_fromDictionaryContainingValueAtIndex_mustReturnValue),
        ("test_subscriptGet_onSequentialEnvironment_fromEmptyArray_mustReturnNil", test_subscriptGet_onSequentialEnvironment_fromEmptyArray_mustReturnNil),
        ("test_subscriptSet_onSequentialEnvironment_mustInsertValueAtIndex", test_subscriptSet_onSequentialEnvironment_mustInsertValueAtIndex),
        ("test_subscriptSetMultipleTimes_onConcurrentEnvironment_mustInsertAllKeyValuePairs", test_subscriptSetMultipleTimes_onConcurrentEnvironment_mustInsertAllKeyValuePairs),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ConcurrentArrayTests.__allTests__ConcurrentArrayTests),
    ]
}
#endif
